packages:
  - packages/*

shamefullyHoist: true
strictPeerDependencies: false
shellEmulator: true
ignoreWorkspaceRootCheck: true

catalogs:
  bundling:
    '@rollup/plugin-alias': ^5.1.1
    '@rollup/plugin-commonjs': ^28.0.8
    '@rollup/plugin-node-resolve': ^16.0.3
    '@unocss/nuxt': ^66.5.4
    '@vueuse/nuxt': ^13.9.0
    esbuild: ^0.25.11
    nitropack: ^2.12.7
    nuxt: ^4.1.3
    nuxt-mcp: ^0.2.4
    rollup: ^4.52.4
    rollup-plugin-esbuild: ^6.2.1
    unbuild: ^3.6.1
    vite: npm:rolldown-vite@latest
  deps:
    ansis: ^4.2.0
    birpc: ^2.6.1
    cac: ^6.7.14
    fast-npm-meta: ^0.4.7
    get-port-please: ^3.2.0
    h3: ^1.15.4
    js-yaml: ^4.1.0
    launch-editor: ^2.11.1
    mrmime: ^2.0.1
    ohash: ^2.0.11
    open: ^10.2.0
    p-limit: ^6.2.0
    package-manager-detector: ^1.4.1
    pathe: ^2.0.3
    publint: ^0.3.14
    semver: ^7.7.3
    stream-json: ^1.9.1
    structured-clone-es: ^1.0.0
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.15
    unconfig: ^7.3.3
    unstorage: ^1.17.1
    ws: ^8.18.3
  dev:
    '@antfu/ni': ^26.2.0
    '@nuxt/devtools': ^2.6.5
    bumpp: ^10.3.1
    typescript: ^5.9.3
    vite-plugin-inspect: ^11.3.3
    vue-tsc: ^3.1.1
  frontend:
    '@webcontainer/api': ^1.6.1
    '@xterm/addon-fit': ^0.10.0
    '@xterm/xterm': ^5.5.0
    d3: ^7.9.0
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    idb-keyval: ^6.2.2
    modern-screenshot: ^4.6.6
    nanovis: ^1.0.0
    theme-vitesse: ^1.0.0
    vite-hot-client: ^2.1.0
  icons:
    '@iconify-json/carbon': ^1.2.14
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/logos': ^1.2.9
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.6
    '@iconify-json/simple-icons': ^1.2.54
  inlined:
    '@antfu/utils': ^9.3.0
  lint:
    '@antfu/eslint-config': ^6.0.0
    '@nuxt/eslint': ^1.9.0
    '@typescript-eslint/utils': ^8.46.1
    '@unocss/eslint-config': ^66.5.4
    eslint: ^9.37.0
    lint-staged: ^16.2.4
    nuxt-eslint-auto-explicit-import: ^0.1.1
    simple-git-hooks: ^2.13.1
  testing:
    mlly: ^1.8.0
    vitest: ^3.2.4
  types:
    '@pnpm/list': ^1000.1.2
    '@pnpm/types': ^1000.8.0
    '@types/connect': ^3.4.38
    '@types/d3': ^7.4.3
    '@types/d3-hierarchy': ^3.1.7
    '@types/js-yaml': ^4.0.9
    '@types/semver': ^7.7.1
    '@types/stream-json': ^1.7.8
    '@types/ws': ^8.18.1
    pkg-types: ^2.3.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - simple-git-hooks
  - unrs-resolver
