packages:
  - packages/*
patchedDependencies:
  nanovis: patches/nanovis.patch
catalogs:
  build:
    '@rollup/plugin-alias': ^5.1.1
    '@rollup/plugin-commonjs': ^28.0.3
    '@rollup/plugin-node-resolve': ^16.0.1
    '@unocss/nuxt': ^66.1.0-beta.10
    '@vueuse/nuxt': ^13.0.0
    esbuild: ^0.25.2
    nitropack: 2.8.1
    nuxt: ~3.15.4
    nuxt-mcp: ^0.0.3
    rollup: ^4.39.0
    rollup-plugin-esbuild: ^6.2.1
    unbuild: ^3.5.0
    vite: ^6.2.5
  deps:
    ansis: ^3.17.0
    birpc: ^2.3.0
    cac: ^6.7.14
    fast-npm-meta: ^0.4.0
    get-port-please: ^3.1.2
    h3: ^1.15.1
    js-yaml: ^4.1.0
    launch-editor: ^2.10.0
    mrmime: ^2.0.1
    ohash: ^2.0.11
    open: ^10.1.0
    p-limit: ^6.2.0
    package-manager-detector: ^1.1.0
    pathe: ^2.0.3
    publint: ^0.3.10
    semver: ^7.7.1
    stream-json: ^1.9.1
    structured-clone-es: ^1.0.0
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.12
    unconfig: ^7.3.1
    unstorage: ^1.15.0
    ws: ^8.18.1
  devtools:
    '@antfu/eslint-config': ^4.11.0
    '@nuxt/devtools': ^2.3.2
    '@nuxt/eslint': ^1.3.0
    '@typescript-eslint/utils': ^8.29.1
    '@unocss/eslint-config': ^66.1.0-beta.10
    bumpp: ^10.1.0
    eslint: ^9.24.0
    lint-staged: ^15.5.0
    nuxt-eslint-auto-explicit-import: ^0.1.1
    simple-git-hooks: ^2.12.1
    typescript: ^5.8.3
    vite-plugin-inspect: ^11.0.0
    vue-tsc: ^2.2.8
  frontend:
    '@webcontainer/api': ^1.5.3
    '@xterm/addon-fit': ^0.10.0
    '@xterm/xterm': ^5.5.0
    d3: ^7.9.0
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    idb-keyval: ^6.2.1
    modern-screenshot: ^4.6.0
    nanovis: ^0.1.0
    theme-vitesse: ^0.8.3
    vite-hot-client: ^2.0.4
  icons:
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/catppuccin': ^1.2.10
    '@iconify-json/logos': ^1.2.4
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/simple-icons': ^1.2.31
  inlined:
    '@antfu/utils': ^9.2.0
  testing:
    mlly: ^1.7.4
    vitest: ^3.1.1
  types:
    '@pnpm/list': ^1000.0.14
    '@pnpm/types': ^1000.4.0
    '@types/connect': ^3.4.38
    '@types/d3': ^7.4.3
    '@types/d3-hierarchy': ^3.1.7
    '@types/js-yaml': ^4.0.9
    '@types/semver': ^7.7.0
    '@types/stream-json': ^1.7.8
    '@types/ws': ^8.18.1
    pkg-types: ^2.1.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
