packages:
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.3.0
  '@antfu/utils': ^9.1.0
  '@eslint/config-array': ^0.19.2
  '@iconify-json/carbon': ^1.2.7
  '@iconify-json/catppuccin': ^1.2.8
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.25
  '@nuxt/devtools': ^2.1.0
  '@nuxt/eslint': ^1.1.0
  '@pnpm/list': ^1000.0.8
  '@pnpm/types': ^1000.1.1
  '@rollup/plugin-alias': ^5.1.1
  '@rollup/plugin-commonjs': ^28.0.2
  '@rollup/plugin-node-resolve': ^16.0.0
  '@shikijs/langs-precompiled': ^3.0.0
  '@shikijs/transformers': ^3.0.0
  '@types/connect': ^3.4.38
  '@types/d3': ^7.4.3
  '@types/d3-hierarchy': ^3.1.7
  '@types/picomatch': ^3.0.2
  '@types/semver': ^7.5.8
  '@types/stream-json': ^1.7.8
  '@types/ws': ^8.5.14
  '@typescript-eslint/utils': ^8.24.1
  '@unocss/eslint-config': ^66.0.0
  '@unocss/nuxt': ^66.0.0
  '@vueuse/nuxt': ^12.7.0
  '@webcontainer/api': ^1.5.1
  '@xterm/addon-fit': ^0.10.0
  '@xterm/xterm': ^5.5.0
  birpc: ^2.2.0
  bumpp: ^10.0.3
  bundle-require: ^5.1.0
  cac: ^6.7.14
  chalk: ^5.4.1
  chokidar: ^4.0.3
  d3: ^7.9.0
  d3-hierarchy: ^3.1.2
  d3-shape: ^3.2.0
  debug: ^4.4.0
  esbuild: ^0.25.0
  eslint: ^9.20.1
  fast-glob: ^3.3.3
  fast-npm-meta: ^0.3.1
  find-up: ^7.0.0
  flatted: ^3.3.3
  floating-vue: ^5.2.2
  fuse.js: ^7.1.0
  get-port-please: ^3.1.2
  h3: ^1.15.0
  idb-keyval: ^6.2.1
  launch-editor: ^2.10.0
  lint-staged: ^15.4.3
  mlly: ^1.7.4
  modern-screenshot: ^4.6.0
  mrmime: ^2.0.1
  nitropack: 2.8.1
  nuxt: ^3.15.4
  nuxt-eslint-auto-explicit-import: ^0.1.1
  open: ^10.1.0
  p-limit: ^6.2.0
  package-manager-detector: ^0.2.9
  pathe: ^2.0.3
  picocolors: ^1.1.1
  picomatch: ^4.0.2
  pkg-types: ^1.3.1
  rollup: ^4.34.8
  rollup-plugin-esbuild: ^6.2.0
  semver: ^7.7.1
  shiki: ^3.0.0
  simple-git-hooks: ^2.11.1
  stream-json: ^1.9.1
  structured-clone-es: ^1.0.0
  theme-vitesse: ^0.8.3
  tinyexec: ^0.3.2
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unconfig: ^7.0.0
  unstorage: ^1.14.4
  vite: ^6.1.0
  vite-hot-client: ^2.0.4
  vite-plugin-inspect: ^10.2.1
  vitest: ^3.0.5
  vue-tsc: ^2.2.2
  ws: ^8.18.0
