packages:
  - packages/*

catalogs:
  devtools:
    '@antfu/eslint-config': ^4.6.0
    '@eslint/config-array': ^0.19.2
    '@nuxt/devtools': ^2.2.1
    '@nuxt/eslint': ^1.1.0
    bumpp: ^10.0.3
    vite-plugin-inspect: ^11.0.0
    nuxt-eslint-auto-explicit-import: ^0.1.1
    '@typescript-eslint/utils': ^8.26.0
    '@unocss/eslint-config': ^66.0.0
    lint-staged: ^15.4.3
    vue-tsc: ^2.2.8
    typescript: ^5.8.2
    simple-git-hooks: ^2.11.1
  types:
    '@types/connect': ^3.4.38
    '@types/d3': ^7.4.3
    '@types/d3-hierarchy': ^3.1.7
    '@types/semver': ^7.5.8
    '@types/stream-json': ^1.7.8
    '@types/ws': ^8.18.0
    '@pnpm/list': ^1000.0.10
    '@pnpm/types': ^1000.2.1
    eslint: ^9.21.0
    pkg-types: ^2.1.0
  icons:
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/catppuccin': ^1.2.9
    '@iconify-json/logos': ^1.2.4
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/simple-icons': ^1.2.27
  deps:
    cac: ^6.7.14
    birpc: ^2.2.0
    ansis: ^3.17.0
    unconfig: ^7.3.0
    unstorage: ^1.15.0
    ws: ^8.18.1
    publint: ^0.3.8
    mrmime: ^2.0.1
    ohash: ^2.0.11
    open: ^10.1.0
    get-port-please: ^3.1.2
    p-limit: ^6.2.0
    stream-json: ^1.9.1
    structured-clone-es: ^1.0.0
    fast-npm-meta: ^0.3.1
    launch-editor: ^2.10.0
    package-manager-detector: ^0.2.11
    pathe: ^2.0.3
    semver: ^7.7.1
    tinyexec: ^0.3.2
    h3: ^1.15.1
  build:
    esbuild: ^0.25.0
    nitropack: 2.8.1
    nuxt: ^3.15.4
    unbuild: ^3.5.0
    vite: ^6.2.0
    '@rollup/plugin-alias': ^5.1.1
    '@rollup/plugin-commonjs': ^28.0.2
    '@rollup/plugin-node-resolve': ^16.0.0
    '@unocss/nuxt': ^66.0.0
    '@vueuse/nuxt': ^12.8.2
    rollup: 4.34.6
    rollup-plugin-esbuild: ^6.2.1
  testing:
    vitest: ^3.0.7
    mlly: ^1.7.4
  fontend:
    vite-hot-client: ^2.0.4
    '@webcontainer/api': ^1.5.1
    '@xterm/addon-fit': ^0.10.0
    '@xterm/xterm': ^5.5.0
    theme-vitesse: ^0.8.3
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    modern-screenshot: ^4.6.0
    d3: ^7.9.0
    idb-keyval: ^6.2.1
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
  inlined:
    '@antfu/utils': ^9.1.0
