trustPolicy: no-downgrade

packages:
  - packages/*

shamefullyHoist: true
strictPeerDependencies: false
shellEmulator: true
ignoreWorkspaceRootCheck: true
trustPolicyExclude:
  - undici-types@6.20.0

catalogs:
  bundling:
    '@rollup/plugin-alias': ^6.0.0
    '@rollup/plugin-commonjs': ^29.0.0
    '@rollup/plugin-node-resolve': ^16.0.3
    '@unocss/nuxt': ^66.6.0
    '@vueuse/nuxt': ^14.2.0
    esbuild: ^0.27.3
    nitropack: ^2.13.1
    nuxt: ^4.3.0
    nuxt-mcp-dev: ^0.3.2
    rollup: ^4.57.1
    rollup-plugin-esbuild: ^6.2.1
    unbuild: ^3.6.1
    vite: ^8.0.0-beta.13
  deps:
    ansis: ^4.2.0
    birpc: ^4.0.0
    cac: ^6.7.14
    fast-npm-meta: ^1.2.0
    get-port-please: ^3.2.0
    h3: ^1.15.5
    js-yaml: ^4.1.1
    launch-editor: ^2.12.0
    mrmime: ^2.0.1
    ohash: ^2.0.11
    open: ^11.0.0
    p-limit: ^7.3.0
    package-manager-detector: ^1.6.0
    pathe: ^2.0.3
    publint: ^0.3.17
    semver: ^7.7.4
    stream-json: ^1.9.1
    structured-clone-es: ^1.0.0
    tinyexec: ^1.0.2
    tinyglobby: ^0.2.15
    unconfig: ^7.4.2
    unstorage: ^1.17.4
    ws: ^8.19.0
  dev:
    '@antfu/ni': ^28.2.0
    '@nuxt/devtools': ^3.1.1
    bumpp: ^10.4.1
    chokidar: ^5.0.0
    typescript: ^5.9.3
    vite-plugin-inspect: ^11.3.3
    vue-tsc: ^3.2.4
  frontend:
    '@webcontainer/api': ^1.6.1
    '@xterm/addon-fit': ^0.11.0
    '@xterm/xterm': ^6.0.0
    d3: ^7.9.0
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    idb-keyval: ^6.2.2
    modern-screenshot: ^4.6.8
    nanovis: ^1.0.0
    theme-vitesse: ^1.0.0
    vite-hot-client: ^2.1.0
  icons:
    '@iconify-json/carbon': ^1.2.18
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.9
    '@iconify-json/simple-icons': ^1.2.69
  inlined:
    '@antfu/utils': ^9.3.0
  lint:
    '@antfu/eslint-config': ^7.2.0
    '@nuxt/eslint': ^1.13.0
    '@typescript-eslint/utils': ^8.54.0
    '@unocss/eslint-config': ^66.6.0
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    nuxt-eslint-auto-explicit-import: ^0.1.1
    simple-git-hooks: ^2.13.1
  testing:
    mlly: ^1.8.0
    type-fest: 4.41.0
    vitest: ^4.0.18
  types:
    '@pnpm/list': ^1000.2.5
    '@pnpm/types': ^1001.3.0
    '@types/connect': ^3.4.38
    '@types/d3': ^7.4.3
    '@types/d3-hierarchy': ^3.1.7
    '@types/js-yaml': ^4.0.9
    '@types/semver': ^7.7.1
    '@types/stream-json': ^1.7.8
    '@types/ws': ^8.18.1
    pkg-types: ^2.3.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - simple-git-hooks
  - unrs-resolver
